In [1]:
def calculatesquare(n):
    return n*n
numbers=(1,2,3,4)
result=map(calculatesquare,numbers)
list(result)

[1, 4, 9, 16]

In [3]:
numbers=(1,2,3,4)
result=map(lambda x: x*x,numbers)
print(result)
list(result)

[1, 4, 9, 16]

In [4]:
num1=[4,5,6]
num2=[5,6,7]
result=map(lambda n1,n2:n1+n2,num1,num2)
list(result)

[9, 11, 13]

In [9]:
people=['Mr. Deva','Mr. surya']
def split_title_and_name(person):
    title=person.split()[0]
    lastname=person.split()[-1]
    return '{} {}'.format(title,lastname)
list(map(split_title_and_name, people))

['Mr. Deva', 'Mr. surya']

In [10]:
dx=lambda x:x*2
print(dx(5))

10


In [11]:
dx=lambda x,y:(x+y)*2
print(dx(5,10))

30


In [12]:
my_list=[1,5,4,6,8,11,3,12]
new_list=map(lambda x:x*2,my_list)
print(list(new_list))

[2, 10, 8, 12, 16, 22, 6, 24]


In [15]:
people=['Dr. brooks','Dr. thompson']
def split_title_and_name(person):
    return person.split()[0]+''+person.split()[-1]

In [16]:
for person in people:
    print(split_title_and_name(person)==(lambda x:x.split()[0]+''+x.split()[-1])(person))

True
True


In [18]:
my_list=[]
for number in range(0,20):
    if number%2==0:
        my_list.append(number)
my_list
        

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [19]:
my_list=[number for number in range(0,20) if number%2==0]
my_list

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [23]:
def times_tables():
    lst=[]
    for i in range(10):
        for j in range(10):
            lst.append(i*j)
    return lst
print(times_tables())
times_tables()==[j*i for i in range(10) for j in range(10)]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 0, 6, 12, 18, 24, 30, 36, 42, 48, 54, 0, 7, 14, 21, 28, 35, 42, 49, 56, 63, 0, 8, 16, 24, 32, 40, 48, 56, 64, 72, 0, 9, 18, 27, 36, 45, 54, 63, 72, 81]


True

In [26]:
import numpy as np
n=np.arange(0,30,2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [27]:
n=n.reshape(3,5)

In [32]:
import numpy as np
num=np.matrix([[11,121,130],
             [613,34,13],
             [514,50,16]])
print("main diagonal element : \n",np.diag(num))
print("\n diagonal element above main diagonal:\n",np.diag(num,1))
print("\n diagonal element below main diagonal:\n",np.diag(num,-1))


main diagonal element : 
 [11 34 16]

 diagonal element above main diagonal:
 [121  13]

 diagonal element below main diagonal:
 [613  50]


In [33]:
np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [34]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [35]:
p=np.ones([3,3],int)
p

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [36]:
np.vstack([p,2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [37]:
np.hstack([p,2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [38]:
np.hstack([p,2*p,3*p])

array([[1, 1, 1, 2, 2, 2, 3, 3, 3],
       [1, 1, 1, 2, 2, 2, 3, 3, 3],
       [1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [39]:
x=np.array([1,2,3])
y=np.array([4,5,6])
print(x)
print(y)

[1 2 3]
[4 5 6]


In [40]:
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x**2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[ 0.25  0.4   0.5 ]
[1 4 9]


In [41]:
x.dot(y)

32

In [42]:
y.dot(x)

32

In [43]:
z=np.array([y,y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [44]:
print(len(z))

2


In [45]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [46]:
z.T.shape

(3, 2)

In [47]:
z.dtype

dtype('int64')

In [48]:
z=z.astype('f')
z.dtype

dtype('float32')

In [51]:
a=np.array([-4,-2,1,3,5])
a.sum()

3

In [52]:

a.max()

5

In [53]:
a.mean()

0.59999999999999998

In [54]:
a.std()

3.2619012860600183

In [55]:
a.min()

-4

In [56]:
a.argmax()

4

In [57]:
a.argmin()

0

In [59]:
s=np.arange(6)
s

array([0, 1, 2, 3, 4, 5])

In [60]:
s=np.arange(6)**2
s

array([ 0,  1,  4,  9, 16, 25])

In [61]:
s[0],s[4],s[-1]

(0, 16, 25)

In [62]:
s[1:5]

array([ 1,  4,  9, 16])

In [63]:
s[-4:]

array([ 4,  9, 16, 25])

In [64]:
s[-5::-2]

array([1])

In [67]:
r=np.arange(100)
r.resize((10,10))
print("\n diagonal element above main diagonal:\n",np.diag(r,1))
print("\n diagonal element below main diagonal:\n",np.diag(r,-1))
r


 diagonal element above main diagonal:
 [ 1 12 23 34 45 56 67 78 89]

 diagonal element below main diagonal:
 [10 21 32 43 54 65 76 87 98]


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [68]:
r[2,2]

22

In [69]:
r[3,3:6]

array([33, 34, 35])

In [70]:
r[:2,:-1]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [10, 11, 12, 13, 14, 15, 16, 17, 18]])

In [71]:
r[-1,::2]

array([90, 92, 94, 96, 98])

In [72]:
r[r>30]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
       65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
       82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,
       99])

In [74]:
r[r>30]=30
r

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30]])

In [76]:
r2=r[:3,:3]
r2

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [77]:
r2[:]=0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [78]:
r


array([[ 0,  0,  0,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0, 23, 24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30]])

In [79]:
r_copy=r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0, 23, 24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30]])

In [80]:
r_copy[:]=10
print(r_copy,'\n')
print(r)

[[10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]] 

[[ 0  0  0  3  4  5  6  7  8  9]
 [ 0  0  0 13 14 15 16 17 18 19]
 [ 0  0  0 23 24 25 26 27 28 29]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]]


In [81]:
test=np.random.randint(0,10,(4,3))
test


array([[3, 8, 1],
       [7, 9, 2],
       [2, 1, 5],
       [2, 1, 8]])

In [82]:
for i in range(len(test)):
    print(test[i])

[3 8 1]
[7 9 2]
[2 1 5]
[2 1 8]


In [83]:
for i,row in enumerate(test):
    print('row',i,'is',row)

row 0 is [3 8 1]
row 1 is [7 9 2]
row 2 is [2 1 5]
row 3 is [2 1 8]


In [86]:
test2=test**2
test2

array([[ 9, 64,  1],
       [49, 81,  4],
       [ 4,  1, 25],
       [ 4,  1, 64]])

In [85]:
for i,j in zip(test,test2):
    print(i,'+',j,'=',i+j)

[3 8 1] + [ 9 64  1] = [12 72  2]
[7 9 2] + [49 81  4] = [56 90  6]
[2 1 5] + [ 4  1 25] = [ 6  2 30]
[2 1 8] + [ 4  1 64] = [ 6  2 72]
